# Generated by Django 5.1.4 on 2024-12-12 03:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('building_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('num_rooms', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stud_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityDirector',
            fields=[
                ('pidm', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('building_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingapp.building')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_num', models.IntegerField(primary_key=True, serialize=False)),
                ('num_beds', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('status', models.CharField(choices=[('open', 'open'), ('closed', 'closed'), ('unrentable', 'unrentable')], default='open', max_length=20)),
                ('deletable', models.BooleanField(default=False)),
                ('building_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingapp.building')),
                ('cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingapp.communitydirector')),
            ],
            options={
                'unique_together': {('room_num', 'building_code')},
            },
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('room_num', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='housingapp.room')),
                ('stud_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingapp.student')),
            ],
            options={
                'unique_together': {('stud_ID', 'room_num')},
            },
        ),
    ]
